# htaccess for Google App Engine
application: phoxy-bootstrap
version: 1
runtime: php55
api_version: 1

default_expiration: "10m"

handlers:
- url: /enjs.js
  static_files: vendor/phoxy/enjs/enjs.js
  upload: vendor/phoxy/enjs/enjs.js

- url: /(.+\.(css|js|ejs))$
  static_files: \1
  upload: .+\.(css|js|ejs)$

- url: /api/.*
  script: rpc.php

- url: /.*
  script: engine/coldstart.php

skip_files:
- .git.*
